# Generated by Django 6.0.3 on 2026-04-08 20:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranzas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cobro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('abierto', 'Abierto'), ('cerrado', 'Cerrado'), ('anulado', 'Anulado')], default='abierto', max_length=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cobros_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ItemCobro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_servicio', models.DecimalField(decimal_places=2, help_text='Snapshot del monto del servicio al momento del cobro', max_digits=12)),
                ('monto_adicional', models.DecimalField(decimal_places=2, default=0, help_text='Cargo adicional (nuestra ganancia)', max_digits=12)),
                ('canal', models.CharField(choices=[('pagofacil', 'Pago Fácil'), ('rapipago', 'Rapipago'), ('otro', 'Otro')], default='pagofacil', max_length=20)),
                ('orden', models.PositiveSmallIntegerField(default=0, help_text='Orden de carga en el carrito')),
                ('cobro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cobranzas.cobro')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cobros', to='cobranzas.servicio')),
            ],
            options={
                'ordering': ['orden', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='PagoCobro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('debito', 'Débito'), ('credito', 'Crédito'), ('qr', 'QR')], max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cobro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='cobranzas.cobro')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
    ]
