# Generated by Django 6.0.3 on 2026-04-13 19:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranzas', '0002_cobro_itemcobro_pagocobro'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcobro',
            name='monto_adicional',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='itemcobro',
            name='monto_servicio',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='itemcobro',
            name='orden',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='CierreDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_desde', models.DateField(help_text='Primer día del rango de turnos incluidos')),
                ('fecha_hasta', models.DateField(help_text='Último día del rango de turnos incluidos')),
                ('cant_turnos', models.PositiveSmallIntegerField(default=0)),
                ('total_efectivo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_transferencia', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_debito', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_credito', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_qr', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_retiros', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_general', models.DecimalField(decimal_places=2, default=0, help_text='Suma de todos los métodos de pago', max_digits=12)),
                ('total_adicionales', models.DecimalField(decimal_places=2, default=0, help_text='Nuestra ganancia del día', max_digits=12)),
                ('efectivo_fisico', models.DecimalField(decimal_places=2, default=0, help_text='Efectivo contado físicamente al cierre', max_digits=12)),
                ('diferencia_caja', models.DecimalField(decimal_places=2, default=0, help_text='efectivo_fisico − efectivo esperado', max_digits=12)),
                ('realizado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cierres_diarios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(editable=False, unique=True)),
                ('estado', models.CharField(choices=[('abierto', 'Abierto'), ('cerrado', 'Cerrado')], default='abierto', max_length=10)),
                ('monto_inicial', models.DecimalField(decimal_places=2, default=0, help_text='Efectivo con que abre la caja (fondo para vueltos)', max_digits=12)),
                ('fecha_apertura', models.DateTimeField(auto_now_add=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('efectivo_declarado', models.DecimalField(blank=True, decimal_places=2, help_text='Efectivo físico contado al cierre', max_digits=12, null=True)),
                ('total_efectivo_sistema', models.DecimalField(blank=True, decimal_places=2, help_text='Efectivo cobrado según el sistema', max_digits=12, null=True)),
                ('diferencia', models.DecimalField(blank=True, decimal_places=2, help_text='efectivo_declarado − efectivo_esperado', max_digits=12, null=True)),
                ('tipo_diferencia', models.CharField(blank=True, choices=[('sobrante', 'Sobrante'), ('faltante', 'Faltante'), ('sin_diferencia', 'Sin diferencia')], max_length=20, null=True)),
                ('cajero', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turnos', to=settings.AUTH_USER_MODEL)),
                ('cierre_diario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turnos', to='cobranzas.cierrediario')),
            ],
            options={
                'ordering': ['-fecha_apertura'],
            },
        ),
        migrations.CreateModel(
            name='RetiroCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(max_length=200)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True, help_text='False = anulado, no cuenta en el balance')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retiros_registrados', to=settings.AUTH_USER_MODEL)),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retiros', to='cobranzas.turno')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddField(
            model_name='cobro',
            name='turno',
            field=models.ForeignKey(blank=True, help_text='Turno en que se realizó el cobro', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cobros', to='cobranzas.turno'),
        ),
    ]
