# Generated by Django 6.0.3 on 2026-04-24 22:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranzas', '0003_alter_itemcobro_monto_adicional_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositoCajaGrande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('monto', models.DecimalField(decimal_places=2, help_text='Monto retirado de la caja grande', max_digits=12)),
                ('observaciones', models.TextField(blank=True)),
                ('realizado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depositos_caja_grande', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Depósito de caja grande',
                'verbose_name_plural': 'Depósitos de caja grande',
                'ordering': ['-fecha'],
            },
        ),
    ]
