# Generated by Django 6.0.3 on 2026-04-25 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranzas', '0004_depositocajagrande'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositoBancario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entidad', models.CharField(choices=[('pagofacil', 'PagoFácil'), ('rapipago', 'RapiPago')], max_length=20)),
                ('fecha', models.DateField(help_text='Fecha en que se realizó el depósito')),
                ('monto', models.DecimalField(decimal_places=2, help_text='Monto depositado en el banco', max_digits=12)),
                ('numero_comprobante', models.CharField(blank=True, help_text='Número de boleta o comprobante bancario', max_length=100)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, help_text='Momento en que se cargó en el sistema')),
                ('realizado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depositos_bancarios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Depósito bancario',
                'verbose_name_plural': 'Depósitos bancarios',
                'ordering': ['-fecha', '-fecha_registro'],
            },
        ),
        migrations.DeleteModel(
            name='DepositoCajaGrande',
        ),
    ]
