# Generated by Django 6.0.3 on 2026-05-06 00:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranzas', '0005_depositobancario_delete_depositocajagrande'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecaudacionDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entidad', models.CharField(choices=[('pagofacil', 'PagoFácil'), ('rapipago', 'RapiPago')], max_length=20)),
                ('fecha', models.DateField(help_text='Fecha de la recaudación')),
                ('monto', models.DecimalField(decimal_places=2, help_text='Monto recaudado en el día', max_digits=12)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, help_text='Momento en que se cargó en el sistema')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recaudaciones_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recaudación diaria',
                'verbose_name_plural': 'Recaudaciones diarias',
                'ordering': ['-fecha', '-fecha_registro'],
                'unique_together': {('entidad', 'fecha')},
            },
        ),
    ]
