# Generated by Django 6.0.3 on 2026-07-30 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranzas', '0006_recaudaciondiaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='familia',
            field=models.CharField(blank=True, db_index=True, help_text='Agrupa los tramos de un mismo servicio escalonado (ej: CF, EX, TNBV)', max_length=20),
        ),
        migrations.AddField(
            model_name='servicio',
            name='rango_desde',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Solo si tipo_precio='rango': monto mínimo de boleta cubierto por este tramo", max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='rango_hasta',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Solo si tipo_precio='rango': monto máximo de boleta cubierto por este tramo", max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='tipo_precio',
            field=models.CharField(choices=[('fijo', 'Fijo'), ('rango', 'Por rango')], default='fijo', max_length=10),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='monto',
            field=models.DecimalField(decimal_places=2, help_text="Precio fijo, o adicional a cobrar cuando tipo_precio='rango'", max_digits=12),
        ),
    ]
