# Generated by Django 6.0.3 on 2026-07-30 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranzas', '0007_servicio_familia_servicio_rango_desde_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositobancario',
            name='diferencia',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='monto − pendiente de depositar en ese momento. Positivo = sobrante, negativo = faltante.', max_digits=12, null=True),
        ),
    ]
