# Generated by Django 6.0.3 on 2026-08-13 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranzas', '0008_depositobancario_diferencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrefijoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'verbose_name': 'Prefijo de servicio',
                'verbose_name_plural': 'Prefijos de servicio',
                'ordering': ['codigo'],
            },
        ),
    ]
