# Generated by Django 6.0.3 on 2026-08-13 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranzas', '0009_prefijoservicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositobancario',
            name='tipo_deposito',
            field=models.CharField(blank=True, choices=[('efectivo_fisico', 'Efectivo físico'), ('ya_en_banco', 'Ya estaba en el banco'), ('saldo_plataforma', 'Saldo a favor en la plataforma')], help_text='Efectivo físico depositado, dinero que ya estaba en el banco (ej. transferencias directas), o saldo a favor reconocido en la propia plataforma (Rapipago/PagoFácil).', max_length=20),
        ),
    ]
