# Generated by Django 6.0.3 on 2026-08-13 20:41

import areas.cobranzas.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranzas', '0010_depositobancario_tipo_deposito'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositoTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, help_text='Foto o captura del comprobante', null=True, upload_to=areas.cobranzas.models._ticket_deposito_path)),
                ('fecha_hora_ticket', models.DateTimeField(blank=True, help_text='Fecha y hora que figura en el comprobante', null=True)),
                ('monto_ticket', models.DecimalField(blank=True, decimal_places=2, help_text='Monto que figura en el comprobante (puede diferir del monto cargado en el depósito)', max_digits=12, null=True)),
                ('numero_operacion', models.CharField(blank=True, max_length=100)),
                ('banco', models.CharField(blank=True, max_length=100)),
                ('titular_nombre', models.CharField(blank=True, max_length=150)),
                ('titular_cuit', models.CharField(blank=True, max_length=30)),
                ('cuenta_origen', models.CharField(blank=True, help_text='Ej: CA$ N° 4085782-3 071-4', max_length=150)),
                ('destinatario', models.CharField(blank=True, help_text='Solo transferencias: razón social/nombre del destinatario', max_length=150)),
                ('cuenta_destino', models.CharField(blank=True, help_text='Solo transferencias: CBU/cuenta destino', max_length=150)),
                ('sucursal', models.CharField(blank=True, help_text='Solo depósitos en efectivo: sucursal/terminal/dirección', max_length=150)),
                ('concepto', models.CharField(blank=True, max_length=150)),
                ('estado', models.CharField(blank=True, help_text="Ej: 'Depósito confirmado'", max_length=100)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_carga', models.DateTimeField(auto_now=True)),
                ('cargado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_depositos', to=settings.AUTH_USER_MODEL)),
                ('deposito', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='cobranzas.depositobancario')),
            ],
        ),
    ]
