# Generated by Django 6.0.3 on 2026-08-17 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranzas', '0011_depositoticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositobancario',
            name='neto_a_depositar_momento',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Recaudado pendiente − saldo anterior: lo que había que depositar en este ciclo, antes de este depósito.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='depositobancario',
            name='periodo_desde_momento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='depositobancario',
            name='periodo_hasta_momento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='depositobancario',
            name='recaudado_pendiente_momento',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Suma de recaudación del período cubierto, antes de descontar el saldo anterior.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='depositobancario',
            name='saldo_anterior_momento',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Diferencia del depósito anterior (con signo) vigente al momento de registrar este depósito.', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='depositobancario',
            name='tipo_deposito',
            field=models.CharField(blank=True, choices=[('efectivo_fisico', 'Efectivo físico'), ('ya_en_banco', 'Ya estaba en el banco'), ('saldo_plataforma', 'Saldo a favor en la plataforma (carga inicial o corrección)')], help_text="Efectivo físico y 'ya estaba en el banco' se cargan cada vez que corresponda. 'Saldo a favor en la plataforma' es distinto: se carga una sola vez (al arrancar, o para corregir un desvío) — después el sistema arrastra ese saldo solo con cada diferencia, no hay que volver a cargarlo cada ciclo.", max_length=20),
        ),
    ]
