# Generated by Django 6.0.3 on 2026-08-17 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranzas', '0012_depositobancario_neto_a_depositar_momento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recaudaciondiaria',
            name='cubierta_por',
            field=models.ForeignKey(blank=True, help_text='Depósito que saldó esta recaudación. NULL = todavía pendiente de depositar.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recaudaciones_cubiertas', to='cobranzas.depositobancario'),
        ),
    ]
