# Generated by Django 6.0.3 on 2026-08-17 19:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranzas', '0013_recaudaciondiaria_cubierta_por'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GastoGanancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.localdate, help_text='Fecha en que se entregó/usó el dinero')),
                ('persona', models.CharField(help_text='Quién lo usó. Texto libre: puede ser un usuario del sistema o simplemente el nombre de una persona.', max_length=150)),
                ('motivo', models.CharField(help_text='Para qué se usó', max_length=300)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gastos_ganancias_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gasto de ganancias',
                'verbose_name_plural': 'Gastos de ganancias',
                'ordering': ['-fecha', '-fecha_registro'],
            },
        ),
    ]
