# Generated by Django 6.0.3 on 2026-08-17 20:55

from decimal import Decimal
from django.db import migrations, models


def backfill_montos_desde_tipo(apps, schema_editor):
    """
    Traduce el viejo tipo_deposito (un solo tipo por fila) a los nuevos 3
    campos de monto, para no perder la composición de los depósitos ya
    cargados antes de borrar tipo_deposito.
    """
    DepositoBancario = apps.get_model('cobranzas', 'DepositoBancario')
    for d in DepositoBancario.objects.all():
        if d.tipo_deposito == 'ya_en_banco':
            d.monto_ya_en_banco = d.monto
        elif d.tipo_deposito == 'saldo_plataforma':
            d.monto_saldo_plataforma = d.monto
        else:
            # 'efectivo_fisico' o vacío/desconocido -> efectivo físico por defecto
            d.monto_efectivo_fisico = d.monto
        d.save(update_fields=['monto_efectivo_fisico', 'monto_ya_en_banco', 'monto_saldo_plataforma'])


class Migration(migrations.Migration):

    dependencies = [
        ('cobranzas', '0014_gastoganancia'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositobancario',
            name='monto_efectivo_fisico',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Efectivo físico depositado en este registro', max_digits=12),
        ),
        migrations.AddField(
            model_name='depositobancario',
            name='monto_saldo_plataforma',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text="Corrección/agregado manual al saldo a favor en la plataforma. Normalmente 0 — el saldo a favor ya se arrastra solo vía 'diferencia', no hace falta cargarlo cada ciclo. Completar solo para corregir un desvío.", max_digits=12),
        ),
        migrations.AddField(
            model_name='depositobancario',
            name='monto_ya_en_banco',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Dinero que ya estaba en el banco (transferencias directas)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='depositobancario',
            name='monto',
            field=models.DecimalField(decimal_places=2, help_text='Monto total depositado (suma de los 3 componentes de arriba)', max_digits=12),
        ),
        migrations.RunPython(backfill_montos_desde_tipo, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='depositobancario',
            name='tipo_deposito',
        ),
    ]
