# Generated by Django 6.0.3 on 2026-08-18 01:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranzas', '0015_remove_depositobancario_tipo_deposito_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AjusteSaldoFavor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entidad', models.CharField(choices=[('pagofacil', 'PagoFácil'), ('rapipago', 'RapiPago')], max_length=20)),
                ('fecha', models.DateField(default=django.utils.timezone.localdate, help_text='Fecha en que se usó el saldo a favor')),
                ('monto', models.DecimalField(decimal_places=2, help_text='Cuánto se descontó del saldo a favor', max_digits=12)),
                ('motivo', models.CharField(help_text='Ej: Carga SUBE, recarga celular...', max_length=200)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ajustes_saldo_favor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Uso de saldo a favor',
                'verbose_name_plural': 'Usos de saldo a favor',
                'ordering': ['-fecha', '-fecha_registro'],
            },
        ),
    ]
