# Generated by Django 6.0.3 on 2026-08-18 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranzas', '0016_ajustesaldofavor'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositoticket',
            name='tipo',
            field=models.CharField(choices=[('efectivo_fisico', 'Efectivo físico'), ('ya_en_banco', 'Transferencia al banco'), ('saldo_plataforma', 'Corrección de saldo a favor')], default='efectivo_fisico', help_text='A qué componente del depósito corresponde este comprobante', max_length=20),
        ),
        migrations.AlterField(
            model_name='depositoticket',
            name='deposito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='cobranzas.depositobancario'),
        ),
        migrations.AlterUniqueTogether(
            name='depositoticket',
            unique_together={('deposito', 'tipo')},
        ),
    ]
