# Generated by Django 6.0.3 on 2026-08-18 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranzas', '0017_depositoticket_tipo_alter_depositoticket_deposito_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositoticket',
            name='tipo',
            field=models.CharField(choices=[('efectivo_fisico', 'Efectivo físico'), ('ya_en_banco', 'Transferencia al banco'), ('saldo_plataforma', 'Corrección de saldo a favor'), ('ticket_1', 'Ticket 1'), ('ticket_2', 'Ticket 2')], default='efectivo_fisico', help_text='A qué componente del depósito corresponde este comprobante', max_length=20),
        ),
    ]
