# Generated by Django 6.0.3 on 2026-08-24 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranzas', '0018_alter_depositoticket_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cierrediario',
            name='total_ingresos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='retirocaja',
            name='tipo',
            field=models.CharField(choices=[('retiro', 'Retiro'), ('ingreso', 'Ingreso')], default='retiro', max_length=10),
        ),
    ]
