# Generated by Django 6.0.3 on 2026-08-25 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranzas', '0019_cierrediario_total_ingresos_retirocaja_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cierrediario',
            name='total_extracciones',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Efectivo entregado por servicios de extracción (familia EX)', max_digits=12),
        ),
    ]
