# Generated by Django 6.0.3 on 2026-08-25 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranzas', '0020_cierrediario_total_extracciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraccionCajaGrande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, help_text='Cuánto de la extracción se cubrió con el efectivo de Caja Grande (no el total de la extracción, solo la parte que faltaba en la caja del turno)', max_digits=12)),
                ('efectivo_turno_antes', models.DecimalField(decimal_places=2, help_text='Efectivo esperado del turno justo antes de esta extracción', max_digits=12)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cobro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extracciones_caja_grande', to='cobranzas.cobro')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extracciones_caja_grande', to='cobranzas.turno')),
            ],
            options={
                'verbose_name': 'Extracción cubierta con Caja Grande',
                'verbose_name_plural': 'Extracciones cubiertas con Caja Grande',
                'ordering': ['-fecha'],
            },
        ),
    ]
