# Generated by Django 6.0.3 on 2026-08-28 20:24

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranzas', '0021_extraccioncajagrande'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='adicional_fijo',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text="Solo tipo_precio='fijo': nuestra ganancia por operación. Se cobra ADEMÁS del monto (el cliente paga monto + adicional_fijo). En tipo_precio='rango' no se usa (la ganancia es el campo 'monto').", max_digits=12),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='monto',
            field=models.DecimalField(decimal_places=2, help_text="tipo_precio='fijo': precio base del servicio (lo que cuesta). tipo_precio='rango': adicional a cobrar en ese tramo.", max_digits=12),
        ),
    ]
