# Generated by Django 6.0.3 on 2026-09-05 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranzas', '0022_servicio_adicional_fijo_alter_servicio_monto'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcobro',
            name='cantidad',
            field=models.PositiveIntegerField(default=1, help_text='Unidades de este servicio en la línea (ej: 10 certificados iguales). Solo se usa en servicios de precio fijo. IMPORTANTE: monto_servicio y monto_adicional YA son el total de la línea (unitario × cantidad), así que las sumas de caja / ganancias / recaudaciones no cambian por este campo.'),
        ),
    ]
