# Generated by Django 6.0.3 on 2026-09-05 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranzas', '0023_itemcobro_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ajustesaldofavor',
            name='entidad',
            field=models.CharField(choices=[('pagofacil', 'PagoFácil'), ('rapipago', 'RapiPago'), ('western_union', 'Western Union')], max_length=20),
        ),
        migrations.AlterField(
            model_name='depositobancario',
            name='entidad',
            field=models.CharField(choices=[('pagofacil', 'PagoFácil'), ('rapipago', 'RapiPago'), ('western_union', 'Western Union')], max_length=20),
        ),
        migrations.AlterField(
            model_name='itemcobro',
            name='canal',
            field=models.CharField(choices=[('pagofacil', 'Pago Fácil'), ('rapipago', 'Rapipago'), ('western_union', 'Western Union'), ('otro', 'Otro')], default='pagofacil', max_length=20),
        ),
        migrations.AlterField(
            model_name='recaudaciondiaria',
            name='entidad',
            field=models.CharField(choices=[('pagofacil', 'PagoFácil'), ('rapipago', 'RapiPago'), ('western_union', 'Western Union')], max_length=20),
        ),
    ]
