# Generated by Django 6.0.3 on 2026-08-13 18:09

import areas.software.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0015_alter_usuariopermisooverride_permiso'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicioSoftware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios_software_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Servicio de software',
                'verbose_name_plural': 'Servicios de software',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('categoria', models.CharField(choices=[('puertos', 'Apertura de puertos'), ('deploy', 'Deploy de servicio nuevo'), ('actualizacion', 'Actualización de servicio'), ('otro', 'Otro')], default='otro', max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('contenido', models.TextField(blank=True, help_text='Contenido del script (bash, etc.)')),
                ('archivo', models.FileField(blank=True, help_text='Opcional: subir el archivo original', null=True, upload_to=areas.software.models._script_archivo_path)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scripts_creados', to=settings.AUTH_USER_MODEL)),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scripts_modificados', to=settings.AUTH_USER_MODEL)),
                ('servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scripts', to='software.serviciosoftware')),
            ],
            options={
                'verbose_name': 'Script',
                'verbose_name_plural': 'Scripts',
                'ordering': ['categoria', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='VPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: VPS Principal, VPS Clientes 1', max_length=100, verbose_name='Nombre / alias')),
                ('proveedor', models.CharField(help_text='Ej: Hostinger, DigitalOcean, AWS, Contabo', max_length=100)),
                ('ip', models.GenericIPAddressField(verbose_name='Dirección IP')),
                ('notas', models.TextField(blank=True)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vps_creadas', to=settings.AUTH_USER_MODEL)),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vps_modificadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'VPS',
                'verbose_name_plural': 'VPS',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Instalacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_texto', models.CharField(blank=True, help_text='Usar solo si el cliente no está cargado en el sistema', max_length=150, verbose_name='Cliente (texto libre)')),
                ('dominio', models.CharField(blank=True, max_length=200)),
                ('puerto', models.PositiveIntegerField(blank=True, null=True)),
                ('ruta_proyecto', models.CharField(blank=True, help_text='Ej: /home/deploy/kai-cart-clientex', max_length=300, verbose_name='Ruta del proyecto')),
                ('ruta_service', models.CharField(blank=True, help_text='Ej: /etc/systemd/system/kai-cart-clientex.service', max_length=300, verbose_name='Ruta del .service')),
                ('ruta_conf', models.CharField(blank=True, help_text='Ej: /etc/nginx/sites-available/kai-cart-clientex.conf', max_length=300, verbose_name='Ruta del .conf')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('mantenimiento', 'En mantenimiento')], default='activo', max_length=15)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instalaciones_software', to='core.cliente')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instalaciones_creadas', to=settings.AUTH_USER_MODEL)),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instalaciones_modificadas', to=settings.AUTH_USER_MODEL)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instalaciones', to='software.serviciosoftware')),
                ('vps', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instalaciones', to='software.vps')),
            ],
            options={
                'verbose_name': 'Instalación',
                'verbose_name_plural': 'Instalaciones',
                'ordering': ['-fecha_alta'],
            },
        ),
    ]
