# Generated by Django 6.0.3 on 2026-08-13 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vps',
            name='acceso_ssh',
            field=models.CharField(blank=True, help_text='Ej: ssh root@85.209.92.238', max_length=200, verbose_name='Comando de acceso'),
        ),
        migrations.AddField(
            model_name='vps',
            name='ancho_banda',
            field=models.CharField(blank=True, help_text='Ej: 4 TB', max_length=30, verbose_name='Ancho de banda'),
        ),
        migrations.AddField(
            model_name='vps',
            name='espacio_disco',
            field=models.CharField(blank=True, help_text='Ej: 50 GB', max_length=30, verbose_name='Espacio en disco'),
        ),
        migrations.AddField(
            model_name='vps',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de vencimiento'),
        ),
        migrations.AddField(
            model_name='vps',
            name='memoria',
            field=models.CharField(blank=True, help_text='Ej: 4 GB', max_length=30, verbose_name='Memoria'),
        ),
        migrations.AddField(
            model_name='vps',
            name='nucleos_cpu',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Núcleos de CPU'),
        ),
        migrations.AddField(
            model_name='vps',
            name='plan',
            field=models.CharField(blank=True, help_text='Ej: KVM 1', max_length=100),
        ),
        migrations.AddField(
            model_name='vps',
            name='sistema_operativo',
            field=models.CharField(blank=True, help_text='Ej: Ubuntu 24.04 LTS', max_length=100, verbose_name='Sistema operativo'),
        ),
        migrations.AddField(
            model_name='vps',
            name='usuario_ssh',
            field=models.CharField(blank=True, default='root', max_length=50, verbose_name='Nombre de usuario SSH'),
        ),
        migrations.AlterField(
            model_name='script',
            name='categoria',
            field=models.CharField(default='Otro', max_length=50),
        ),
    ]
