# Generated by Django 6.0.3 on 2026-08-13 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0002_vps_acceso_ssh_vps_ancho_banda_vps_espacio_disco_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='vps',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scripts', to='software.vps', verbose_name='VPS específica'),
        ),
    ]
