# Generated by Django 6.0.3 on 2026-08-18 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0003_script_vps'),
    ]

    operations = [
        migrations.AddField(
            model_name='instalacion',
            name='comandos',
            field=models.TextField(blank=True, help_text='Comandos para actualizar esta instalación puntualmente (ej: cd /home/deploy/proyecto && git pull && systemctl restart proyecto)', verbose_name='Comandos de actualización'),
        ),
    ]
