# Generated by Django 6.0.3 on 2026-08-24 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0004_instalacion_comandos'),
    ]

    operations = [
        migrations.AddField(
            model_name='instalacion',
            name='contrasena_admin',
            field=models.CharField(blank=True, max_length=200, verbose_name='Contraseña'),
        ),
        migrations.AddField(
            model_name='instalacion',
            name='usuario_admin',
            field=models.CharField(blank=True, max_length=100, verbose_name='Usuario (superusuario)'),
        ),
    ]
