# Generated by Django 6.0.3 on 2026-03-22 00:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_usuario_dni_alter_usuario_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='rol',
            name='permisos',
            field=models.TextField(blank=True, default='', help_text='Códigos de permisos separados por coma.'),
        ),
        migrations.CreateModel(
            name='UsuarioPermisoOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permiso', models.CharField(choices=[('ver_usuarios', 'Ver lista de usuarios'), ('crear_usuarios', 'Crear usuarios'), ('editar_usuarios', 'Editar usuarios'), ('eliminar_usuarios', 'Eliminar usuarios'), ('gestionar_permisos', 'Gestionar permisos de otros usuarios')], max_length=50)),
                ('concedido', models.BooleanField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overrides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'permiso')},
            },
        ),
    ]
