# Generated by Django 6.0.3 on 2026-03-22 02:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rol_permisos_usuariopermisooverride'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariopermisooverride',
            name='permiso',
            field=models.CharField(choices=[('ver_usuarios', 'Ver lista de usuarios'), ('crear_usuarios', 'Crear usuarios'), ('editar_usuarios', 'Editar usuarios'), ('eliminar_usuarios', 'Eliminar usuarios'), ('gestionar_permisos', 'Gestionar permisos de otros usuarios'), ('ver_clientes', 'Ver lista de clientes'), ('crear_clientes', 'Crear clientes'), ('editar_clientes', 'Editar clientes'), ('eliminar_clientes', 'Eliminar clientes')], max_length=50),
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('persona', 'Persona física'), ('empresa', 'Empresa / Persona jurídica')], default='persona', max_length=10)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('potencial', 'Potencial'), ('suspendido', 'Suspendido')], default='activo', max_length=15)),
                ('nombre', models.CharField(blank=True, max_length=150)),
                ('apellido', models.CharField(blank=True, max_length=150)),
                ('dni', models.CharField(blank=True, max_length=20, verbose_name='DNI')),
                ('cuil', models.CharField(blank=True, max_length=20, verbose_name='CUIL')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('genero', models.CharField(blank=True, help_text='Ej: masculino, femenino, no binario, prefiero no decir', max_length=20)),
                ('razon_social', models.CharField(blank=True, max_length=200, verbose_name='Razón social')),
                ('nombre_comercial', models.CharField(blank=True, max_length=200, verbose_name='Nombre comercial')),
                ('cuit', models.CharField(blank=True, max_length=20, verbose_name='CUIT')),
                ('cond_iva', models.CharField(blank=True, help_text='Ej: Responsable Inscripto, Monotributista, Exento', max_length=50, verbose_name='Condición ante IVA')),
                ('rubro', models.CharField(blank=True, help_text='Ej: Farmacia, Comercio, Industria, Gastronomía', max_length=100)),
                ('sitio_web', models.URLField(blank=True)),
                ('fecha_fundacion', models.DateField(blank=True, null=True)),
                ('email_principal', models.EmailField(blank=True, max_length=254)),
                ('email_secundario', models.EmailField(blank=True, max_length=254)),
                ('telefono_principal', models.CharField(blank=True, max_length=30)),
                ('telefono_secundario', models.CharField(blank=True, max_length=30)),
                ('whatsapp', models.CharField(blank=True, max_length=30)),
                ('instagram', models.CharField(blank=True, help_text='Usuario de Instagram sin @', max_length=100)),
                ('facebook', models.CharField(blank=True, help_text='URL o nombre de página', max_length=200)),
                ('linkedin', models.URLField(blank=True)),
                ('calle', models.CharField(blank=True, max_length=200)),
                ('numero', models.CharField(blank=True, max_length=20)),
                ('piso_depto', models.CharField(blank=True, max_length=50, verbose_name='Piso / Depto')),
                ('barrio', models.CharField(blank=True, max_length=100)),
                ('localidad', models.CharField(blank=True, max_length=100)),
                ('partido', models.CharField(blank=True, max_length=100, verbose_name='Partido / Municipio')),
                ('provincia', models.CharField(blank=True, max_length=100)),
                ('pais', models.CharField(blank=True, default='Argentina', max_length=100)),
                ('codigo_postal', models.CharField(blank=True, max_length=20, verbose_name='Código postal')),
                ('latitud', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('maps_url', models.URLField(blank=True, help_text='Link directo al lugar en Google Maps', verbose_name='URL de Google Maps')),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='clientes/perfiles/')),
                ('notas', models.TextField(blank=True, verbose_name='Notas internas')),
                ('como_nos_conocio', models.CharField(blank=True, help_text='Ej: referido, redes sociales, publicidad, web', max_length=200, verbose_name='¿Cómo nos conoció?')),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes_creados', to=settings.AUTH_USER_MODEL)),
                ('referido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referidos', to='core.cliente', verbose_name='Referido por')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['apellido', 'nombre', 'razon_social'],
            },
        ),
        migrations.CreateModel(
            name='ClienteContactoAdicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('apellido', models.CharField(blank=True, max_length=150)),
                ('rol', models.CharField(choices=[('administrativo', 'Administrativo'), ('tecnico', 'Técnico'), ('gerencia', 'Gerencia / Dirección'), ('ventas', 'Ventas / Comercial'), ('cobranza', 'Cobranza'), ('otro', 'Otro')], default='otro', max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('whatsapp', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('notas', models.CharField(blank=True, max_length=200)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos_adicionales', to='core.cliente')),
            ],
            options={
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ClienteImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='clientes/galeria/')),
                ('tipo', models.CharField(choices=[('local', 'Foto del local / oficina'), ('fachada', 'Fachada exterior'), ('producto', 'Producto o servicio'), ('documento', 'Documento'), ('otro', 'Otro')], default='otro', max_length=20)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de aparición en la galería')),
                ('subida_el', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='core.cliente')),
            ],
            options={
                'ordering': ['orden', 'subida_el'],
            },
        ),
    ]
