# Generated by Django 6.0.3 on 2026-03-22 02:53

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_usuariopermisooverride_permiso_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienteimagen',
            name='imagen',
            field=models.ImageField(upload_to=core.models._cliente_imagen_path),
        ),
    ]
