# Generated by Django 6.0.3 on 2026-03-23 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_clienteimagen_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoFamiliar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido_referencia', models.CharField(help_text='Apellido o nombre de referencia del grupo. Ej: López, Rodríguez', max_length=100)),
                ('direccion_referencia', models.CharField(blank=True, help_text='Dirección del terreno/edificio compartido', max_length=300)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción adicional del grupo o terreno')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Grupo familiar',
                'verbose_name_plural': 'Grupos familiares',
                'ordering': ['apellido_referencia'],
            },
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='telefono_principal',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='telefono_secundario',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='whatsapp',
        ),
        migrations.AddField(
            model_name='cliente',
            name='canal_preferido',
            field=models.CharField(blank=True, choices=[('whatsapp', 'WhatsApp'), ('llamada', 'Llamada telefónica'), ('email', 'Email'), ('sms', 'SMS'), ('presencial', 'Presencial')], default='whatsapp', max_length=15),
        ),
        migrations.AddField(
            model_name='cliente',
            name='codigo',
            field=models.CharField(blank=True, help_text='Generado automáticamente. Formato: GK-000000-AA', max_length=15, unique=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='fecha_desde_cliente',
            field=models.DateField(blank=True, help_text='Fecha en que se convirtió en cliente', null=True, verbose_name='Cliente desde'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='fecha_proximo_contacto',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='fecha_ultimo_contacto',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nivel_riesgo',
            field=models.CharField(blank=True, choices=[('bajo', 'Bajo'), ('medio', 'Medio'), ('alto', 'Alto')], default='bajo', max_length=10),
        ),
        migrations.AddField(
            model_name='cliente',
            name='ocupacion',
            field=models.CharField(blank=True, help_text='Profesión u ocupación', max_length=100),
        ),
        migrations.AddField(
            model_name='cliente',
            name='scoring',
            field=models.IntegerField(default=1000, help_text='Puntuación del cliente. Inicia en 1000, sube o baja según comportamiento.'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tags',
            field=models.CharField(blank=True, help_text='Etiquetas separadas por coma. Ej: VIP, moroso, potencial', max_length=500),
        ),
        migrations.AddField(
            model_name='cliente',
            name='unidad_habitacional',
            field=models.CharField(blank=True, help_text='Identificador dentro del terreno/edificio. Ej: Casa A, Depto 3B, Lote 2', max_length=50),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='como_nos_conocio',
            field=models.CharField(blank=True, max_length=200, verbose_name='¿Cómo nos conoció?'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cond_iva',
            field=models.CharField(blank=True, max_length=50, verbose_name='Condición ante IVA'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='facebook',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='genero',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='instagram',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='maps_url',
            field=models.URLField(blank=True, verbose_name='URL de mapa'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='rubro',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='clientecontactoadicional',
            name='rol',
            field=models.CharField(choices=[('administrativo', 'Administrativo'), ('tecnico', 'Técnico'), ('gerencia', 'Gerencia / Dirección'), ('ventas', 'Ventas / Comercial'), ('cobranza', 'Cobranza'), ('familiar', 'Familiar'), ('otro', 'Otro')], default='otro', max_length=20),
        ),
        migrations.AlterField(
            model_name='clienteimagen',
            name='orden',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='clienteimagen',
            name='tipo',
            field=models.CharField(choices=[('local', 'Foto del local / oficina'), ('fachada', 'Fachada exterior'), ('producto', 'Producto o servicio'), ('documento', 'Documento'), ('equipo', 'Equipo / Instalación'), ('otro', 'Otro')], default='otro', max_length=20),
        ),
        migrations.CreateModel(
            name='ClienteTelefono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=30)),
                ('tipo', models.CharField(choices=[('movil', 'Móvil'), ('fijo', 'Fijo')], default='movil', max_length=5)),
                ('es_titular', models.BooleanField(default=False, help_text='Número principal de este tipo. Solo uno por tipo por cliente.')),
                ('descripcion', models.CharField(blank=True, help_text='Ej: trabajo, esposa, emergencia', max_length=100)),
                ('tiene_whatsapp', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telefonos', to='core.cliente')),
            ],
            options={
                'verbose_name': 'Teléfono',
                'verbose_name_plural': 'Teléfonos',
                'ordering': ['-es_titular', 'tipo', 'id'],
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='grupo_familiar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes', to='core.grupofamiliar', verbose_name='Grupo familiar / Terreno'),
        ),
    ]
