# Generated by Django 6.0.3 on 2026-03-23 19:46

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_grupofamiliar_remove_cliente_telefono_principal_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AddField(
            model_name='usuario',
            name='alias_cbu',
            field=models.CharField(blank=True, max_length=50, verbose_name='Alias CBU'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='apto_psicofisico',
            field=models.BooleanField(blank=True, null=True, verbose_name='Apto psicofísico'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='area',
            field=models.CharField(blank=True, max_length=100, verbose_name='Área / Departamento'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='banco',
            field=models.CharField(blank=True, max_length=100, verbose_name='Banco'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='barrio',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='usuario',
            name='calle',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='usuario',
            name='cantidad_hijos',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Cantidad de hijos'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='cbu',
            field=models.CharField(blank=True, max_length=30, verbose_name='CBU / CVU'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=20, verbose_name='Código postal'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='cuil',
            field=models.CharField(blank=True, max_length=20, verbose_name='CUIL'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='email_personal',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email personal'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='emergencia_nombre',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nombre contacto emergencia'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='emergencia_telefono',
            field=models.CharField(blank=True, max_length=30, verbose_name='Teléfono emergencia'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='emergencia_vinculo',
            field=models.CharField(blank=True, help_text='Ej: madre, cónyuge, hermano', max_length=80, verbose_name='Vínculo'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('soltero', 'Soltero/a'), ('casado', 'Casado/a'), ('divorciado', 'Divorciado/a'), ('viudo', 'Viudo/a'), ('union', 'Unión convivencial'), ('otro', 'Otro')], max_length=15),
        ),
        migrations.AddField(
            model_name='usuario',
            name='estado_laboral',
            field=models.CharField(blank=True, choices=[('activo', 'Activo'), ('licencia', 'En licencia'), ('suspendido', 'Suspendido'), ('egresado', 'Egresado / Desvinculado'), ('periodo_prueba', 'Período de prueba')], default='activo', max_length=20),
        ),
        migrations.AddField(
            model_name='usuario',
            name='fecha_apto',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha del apto'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='fecha_egreso',
            field=models.DateField(blank=True, help_text='Completar solo si el empleado se retiró.', null=True, verbose_name='Fecha de egreso'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='fecha_ingreso',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de ingreso'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to=core.models._usuario_foto_path, verbose_name='Foto de perfil'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='genero',
            field=models.CharField(blank=True, choices=[('masculino', 'Masculino'), ('femenino', 'Femenino'), ('no_binario', 'No binario'), ('otro', 'Otro'), ('nd', 'Prefiero no decir')], max_length=15),
        ),
        migrations.AddField(
            model_name='usuario',
            name='grupo_sanguineo',
            field=models.CharField(blank=True, help_text='Ej: A+, O-, AB+', max_length=10, verbose_name='Grupo sanguíneo'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='legajo',
            field=models.CharField(blank=True, max_length=30, verbose_name='Nº de legajo'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='localidad',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='usuario',
            name='modalidad_trabajo',
            field=models.CharField(blank=True, choices=[('presencial', 'Presencial'), ('remoto', 'Remoto'), ('hibrido', 'Híbrido')], max_length=15),
        ),
        migrations.AddField(
            model_name='usuario',
            name='nacionalidad',
            field=models.CharField(blank=True, default='Argentina', max_length=100),
        ),
        migrations.AddField(
            model_name='usuario',
            name='notas_internas',
            field=models.TextField(blank=True, verbose_name='Notas internas (RRHH)'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='nro_afiliado',
            field=models.CharField(blank=True, max_length=50, verbose_name='Nº afiliado'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='numero',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='usuario',
            name='obra_social',
            field=models.CharField(blank=True, max_length=150, verbose_name='Obra social / Prepaga'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='observaciones_salud',
            field=models.TextField(blank=True, help_text='Alergias, medicación habitual, condiciones relevantes', verbose_name='Observaciones de salud'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='pais',
            field=models.CharField(blank=True, default='Argentina', max_length=100),
        ),
        migrations.AddField(
            model_name='usuario',
            name='partido',
            field=models.CharField(blank=True, max_length=100, verbose_name='Partido / Municipio'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='piso_depto',
            field=models.CharField(blank=True, max_length=50, verbose_name='Piso / Depto'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='provincia',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='usuario',
            name='puesto',
            field=models.CharField(blank=True, max_length=150, verbose_name='Puesto / Cargo'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='salario_bruto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='sucursal',
            field=models.CharField(blank=True, max_length=100, verbose_name='Sucursal / Sede'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='telefono_alternativo',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='usuario',
            name='telefono_personal',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='usuario',
            name='tiene_hijos',
            field=models.BooleanField(blank=True, null=True, verbose_name='Tiene hijos'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='tipo_contrato',
            field=models.CharField(blank=True, choices=[('indeterminado', 'Tiempo indeterminado'), ('determinado', 'Tiempo determinado'), ('pasantia', 'Pasantía'), ('eventual', 'Eventual / Temporario'), ('prestacion', 'Prestación de servicios (monotributista)'), ('otro', 'Otro')], max_length=20),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fecha_desde_cliente',
            field=models.DateField(blank=True, null=True, verbose_name='Cliente desde'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='ocupacion',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='scoring',
            field=models.IntegerField(default=1000, help_text='Puntuación del cliente. Inicia en 1000.'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='unidad_habitacional',
            field=models.CharField(blank=True, help_text='Ej: Casa A, Depto 3B, Lote 2', max_length=50),
        ),
        migrations.AlterField(
            model_name='clientetelefono',
            name='descripcion',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='clientetelefono',
            name='es_titular',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='dni',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='DNI'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre/s'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Apellido/s'),
        ),
        migrations.CreateModel(
            name='UsuarioCapacitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de la capacitación')),
                ('tipo', models.CharField(choices=[('onboarding', 'Onboarding / Inducción'), ('tecnica', 'Capacitación técnica'), ('seguridad', 'Seguridad e higiene'), ('blandas', 'Habilidades blandas'), ('normativa', 'Normativa / Compliance'), ('producto', 'Producto / Servicio'), ('otro', 'Otro')], default='tecnica', max_length=20)),
                ('modalidad', models.CharField(blank=True, choices=[('presencial', 'Presencial'), ('virtual', 'Virtual / Online'), ('mixta', 'Mixta'), ('autogestivo', 'Autogestivo')], max_length=15)),
                ('proveedor', models.CharField(blank=True, help_text='Empresa, persona o plataforma que dictó la capacitación', max_length=200, verbose_name='Proveedor / Instructor')),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('duracion_hs', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Duración (horas)')),
                ('resultado', models.CharField(choices=[('aprobado', 'Aprobado'), ('desaprobado', 'Desaprobado'), ('en_curso', 'En curso'), ('pendiente', 'Pendiente'), ('no_aplica', 'No aplica')], default='pendiente', max_length=15)),
                ('calificacion', models.DecimalField(blank=True, decimal_places=2, help_text='Nota o puntaje según escala del proveedor', max_digits=5, null=True, verbose_name='Calificación obtenida')),
                ('nota_maxima', models.DecimalField(blank=True, decimal_places=2, help_text='Escala: ej. 10, 100, 5', max_digits=5, null=True, verbose_name='Nota máxima')),
                ('es_obligatoria', models.BooleanField(default=False, verbose_name='Es obligatoria')),
                ('certificado_emitido', models.BooleanField(default=False, verbose_name='Se emitió certificado')),
                ('vencimiento_cert', models.DateField(blank=True, null=True, verbose_name='Vencimiento del certificado')),
                ('observaciones', models.TextField(blank=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capacitaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Capacitación',
                'verbose_name_plural': 'Capacitaciones',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='UsuarioDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('dni', 'DNI / Identidad'), ('contrato', 'Contrato laboral'), ('titulo', 'Título / Certificado de estudios'), ('certificado', 'Certificado de capacitación'), ('apto_medico', 'Apto médico / psicofísico'), ('recibo_sueldo', 'Recibo de sueldo'), ('constancia', 'Constancia (AFIP, obra social, etc.)'), ('obra_social', 'Documentación obra social'), ('otro', 'Otro')], default='otro', max_length=20)),
                ('nombre', models.CharField(max_length=200, verbose_name='Descripción del archivo')),
                ('archivo', models.FileField(upload_to=core.models._usuario_doc_path)),
                ('fecha_doc', models.DateField(blank=True, null=True, verbose_name='Fecha del documento')),
                ('vencimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de vencimiento')),
                ('observaciones', models.CharField(blank=True, max_length=300)),
                ('subido_el', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['-subido_el'],
            },
        ),
        migrations.CreateModel(
            name='UsuarioEstudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('primario', 'Primario'), ('secundario', 'Secundario'), ('terciario', 'Terciario / Técnico'), ('universitario', 'Universitario'), ('posgrado', 'Posgrado / Maestría'), ('doctorado', 'Doctorado'), ('curso', 'Curso / Taller'), ('idioma', 'Idioma'), ('otro', 'Otro')], max_length=20)),
                ('titulo', models.CharField(max_length=200, verbose_name='Título / Carrera')),
                ('institucion', models.CharField(blank=True, max_length=200, verbose_name='Institución')),
                ('estado', models.CharField(choices=[('completo', 'Completo'), ('en_curso', 'En curso'), ('incompleto', 'Incompleto / Abandonado')], default='completo', max_length=15)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de finalización / egreso')),
                ('promedio', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Promedio / calificación')),
                ('observaciones', models.TextField(blank=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Estudio',
                'verbose_name_plural': 'Estudios',
                'ordering': ['-fecha_fin', '-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='UsuarioExperienciaLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=200, verbose_name='Empresa / Empleador')),
                ('puesto', models.CharField(max_length=150, verbose_name='Puesto / Cargo')),
                ('area', models.CharField(blank=True, max_length=100, verbose_name='Área')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción de tareas')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, help_text='Dejar vacío si es el trabajo actual.', null=True)),
                ('trabajo_actual', models.BooleanField(default=False, verbose_name='Es trabajo actual')),
                ('motivo_egreso', models.CharField(blank=True, choices=[('renuncia', 'Renuncia voluntaria'), ('despido', 'Despido'), ('mutuo_acuerdo', 'Mutuo acuerdo'), ('fin_contrato', 'Fin de contrato'), ('cierre', 'Cierre de empresa'), ('otro', 'Otro')], max_length=20)),
                ('referencia_nombre', models.CharField(blank=True, max_length=150, verbose_name='Nombre referencia laboral')),
                ('referencia_contacto', models.CharField(blank=True, help_text='Teléfono o email del referente', max_length=150, verbose_name='Contacto referencia')),
                ('observaciones', models.TextField(blank=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiencias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Experiencia laboral',
                'verbose_name_plural': 'Experiencias laborales',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
