# Generated by Django 6.0.3 on 2026-03-23 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_usuario_options_usuario_alias_cbu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientetelefono',
            name='descripcion',
            field=models.CharField(blank=True, help_text='Ej: trabajo, esposa, emergencia', max_length=100),
        ),
        migrations.AlterField(
            model_name='clientetelefono',
            name='es_titular',
            field=models.BooleanField(default=False, help_text='Número principal de este tipo. Solo uno por tipo por cliente.'),
        ),
        migrations.AlterField(
            model_name='grupofamiliar',
            name='apellido_referencia',
            field=models.CharField(help_text='Apellido o nombre de referencia. Ej: López, Rodríguez', max_length=100),
        ),
        migrations.AlterField(
            model_name='grupofamiliar',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
    ]
