# Generated by Django 6.0.3 on 2026-03-27 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_clientetelefono_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='genero',
            field=models.CharField(blank=True, choices=[('masculino', 'Masculino'), ('femenino', 'Femenino'), ('no_binario', 'No binario'), ('otro', 'Otro'), ('nd', 'Prefiero no decir')], max_length=15),
        ),
    ]
