# Generated by Django 6.0.3 on 2026-03-27 00:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_cliente_genero_alter_usuario_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='genero',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='genero',
            field=models.CharField(blank=True, choices=[('masculino', 'Masculino'), ('femenino', 'Femenino'), ('no_binario', 'No binario'), ('otro', 'Otro'), ('nd', 'Prefiero no decir')], max_length=15),
        ),
        migrations.CreateModel(
            name='UsuarioCuentaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('banco', 'Banco'), ('billetera', 'Billetera virtual'), ('cripto', 'Cripto / Exchange'), ('otro', 'Otro')], default='banco', max_length=15)),
                ('nombre', models.CharField(help_text='Ej: Banco Nación, Mercado Pago, Ualá', max_length=150, verbose_name='Banco / Entidad')),
                ('titular', models.CharField(blank=True, help_text='Solo si difiere del empleado', max_length=150, verbose_name='Titular')),
                ('cbu_cvu', models.CharField(blank=True, max_length=30, verbose_name='CBU / CVU')),
                ('alias', models.CharField(blank=True, max_length=50, verbose_name='Alias')),
                ('nro_cuenta', models.CharField(blank=True, max_length=50, verbose_name='Nº de cuenta')),
                ('es_principal', models.BooleanField(default=False, verbose_name='Cuenta principal (cobro de haberes)')),
                ('observaciones', models.CharField(blank=True, max_length=300)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentas_bancarias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cuenta bancaria',
                'verbose_name_plural': 'Cuentas bancarias',
                'ordering': ['-es_principal', 'nombre'],
            },
        ),
    ]
