# Generated by Django 6.0.3 on 2026-08-13 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_usuariopermisooverride_permiso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariopermisooverride',
            name='permiso',
            field=models.CharField(choices=[('ver_usuarios', 'Ver lista de usuarios'), ('crear_usuarios', 'Crear usuarios'), ('editar_usuarios', 'Editar usuarios'), ('eliminar_usuarios', 'Eliminar usuarios'), ('gestionar_permisos', 'Gestionar permisos de otros usuarios'), ('ver_clientes', 'Ver lista de clientes'), ('crear_clientes', 'Crear clientes'), ('editar_clientes', 'Editar clientes'), ('eliminar_clientes', 'Eliminar clientes'), ('ver_servicios', 'Ver catálogo de servicios'), ('crear_servicios', 'Crear servicios'), ('editar_servicios', 'Editar servicios'), ('eliminar_servicios', 'Eliminar servicios'), ('ver_vps', 'Ver VPS'), ('crear_vps', 'Crear VPS'), ('editar_vps', 'Editar VPS'), ('eliminar_vps', 'Eliminar VPS'), ('ver_servicios_software', 'Ver catálogo de software'), ('crear_servicios_software', 'Crear servicios de software'), ('editar_servicios_software', 'Editar servicios de software'), ('eliminar_servicios_software', 'Eliminar servicios de software'), ('ver_instalaciones', 'Ver instalaciones'), ('crear_instalaciones', 'Crear instalaciones'), ('editar_instalaciones', 'Editar instalaciones'), ('eliminar_instalaciones', 'Eliminar instalaciones'), ('ver_scripts', 'Ver scripts'), ('crear_scripts', 'Crear scripts'), ('editar_scripts', 'Editar scripts'), ('eliminar_scripts', 'Eliminar scripts')], max_length=50),
        ),
    ]
